(project-shell "*shell*" "/home/jan/work/edeposit.amqp.pdfbox")
(project-task run-test "*shell*" "lein test")
(project-task run-test-refresh "*shell*" "lein test-refresh")
(project-task run-pdf "*shell*" "lein run -- --file '/opt/differ/docs/images/PDF/1002186430_000015 Born digital - OCR z TIFFu PDF_A-1a.pdf'")
(project-task run-aa "*shell*" "./aa.py")
